server:
  port: 8000

spring:
  application:
    name: hello-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    preferIpAddress: true
