spring:
  application:
    name: gateway-zuul
server:
  port: 8050
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: client-ui
  routes:
    hello:
      path: /hello/**
      service-id: hello-service
